### ISSUE TITLE
domain 层和 model 层相互依赖

### ISSUE THREAD

**Issue by csgsky** [Lauzy/TicktockMusic#1]
hello，看了您的代码，发现 repository 接口定义在 domain 层，而实现类在 model 层。我的理解是 接口属于业务逻辑。但是却有一点点违背了 clean architecture 的感觉。望不吝赐教。

**Comment by Lauzy** [comment]
有点不太明白你的意思。 domain 是为了让数据层和表现层分开，业务逻辑可以在 domain 中通过接口处理，表现层只用调用 domian 的接口方法就可以获取业务的数据结果，数据具体的增删改查是在 data 层实现的。
